#
# Build stage
#
FROM ubuntu:24.04 AS build-stage

ARG DEBIAN_FRONTEND=noninteractive
# Install dependencies
RUN set -xe; \
	apt-get update; \
	apt-get install --no-install-recommends -y \
		cmake make g++ libssl-dev patch \
		protobuf-compiler libprotobuf-dev \
		qt6-base-dev libqt6opengl6-dev; \
	apt-get clean -y; \
	rm -rf /var/lib/apt/lists/*;

RUN useradd --create-home --shell /bin/bash default
WORKDIR /home/default

COPY . .
RUN set -xe; \
	mkdir build; \
	cd build; \
	cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DRELATIVE_DATA_DIRS=ON ..; \
	make simulator-cli -j $(nproc); \
	cmake --install . --prefix /home/default/install;

#
# Run stage
#
FROM ubuntu:24.04

LABEL maintainer="Robotics Erlangen e.V. <info@robotics-erlangen.de>"

ARG DEBIAN_FRONTEND=noninteractive
RUN set -xe; \
	apt-get update; \
	apt-get install --no-install-recommends -y \
		libqt6core6t64 libqt6gui6t64 libqt6network6t64 libqt6opengl6t64 \
		libprotobuf32t64 tini; \
	apt-get clean -y; \
	rm -rf /var/lib/apt/lists/*;

RUN useradd --create-home --shell /bin/bash default
USER default
WORKDIR /home/default

COPY --chown=default:default --from=build-stage /home/default/install/bin/simulator-cli bin/simulator-cli
COPY --chown=default:default --from=build-stage /home/default/install/config config

# 10300: Control - Accepts simulator configuration commands
# 10301: Blue    - Accepts robot commands by the blue team
# 10302: Yellow  - Accepts robot commands by the yellow team
EXPOSE 10300 10301 10302

ENTRYPOINT ["tini", "--"]
CMD ["./bin/simulator-cli"]
