name: docker build

on:
  push:
    branches:
      - master
      - docker-build
  workflow_dispatch:
jobs:
  docker_build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: data/docker/Dockerfile.simulatorcli
          push: true
          tags: ghcr.io/${{ github.repository }}:simulatorcli
          cache-from: type=gha
          cache-to: type=gha,mode=max
